apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    DB_PASSWORD: AgBX1b1cp1GX5IbBneJ9FZswBMohxLDLgIenyGoKLZNUMGDOiKRM4ZLvZTkjdPvSta7u52l33Uqp1SCGRyLXrWir4OZ5XDne+sMHmuoBot5agaF1LgWc8LxfXciyWVqQGA5OnV5wJEcTbFQpAgXu+j38cD0wNrZDXP0k3oKmkdGxkT2oHAaYvGUGFtQm+39yxYmhGQvNZFJH8kebkOJuVlubh/QfcWQjEkpGx1x4N/Ax13GWP/4DoPJEP/vq+XNSx8swg9OxqUmxcamfiyWArZCWw0YCiqOGaDTzbqpDY6Gw9uMe5N8HrCptSKfH36FxIwRsujNc0lifjExxv+d2HGkMD3Z3YtH668UAt+i/AzynQjSn4FRSqjwuASi7cSKyWVA4kgK+B1DssVu72jZ7TAoaVE1FuYlFGk6iHIxi1CwlzKcv80IU3COlM0ShUeOA/jzyZMU8GrLMvL+7w1pX+hV97FeK9Ve2ikc2zpJf/RS+GktR8fEQ+B04ehaiaxAq6AkwKI1IWwlA7iHuGs+h3373EvugM6cNz81MZezTfUmEGt8rrq5rMZ3cvMvFPXQwWmPIHHrrMpozNv6MGehM/PiT15k0GEIggc+jRVVQbnx4g9wt4joZMQkpR0hUqtLTpFDKh+ZJWUxJn0kiPE+ocnVWGMyOp+om4onJHBapXIXyry3Xg9y2Q6M4iZaDffS6ilpkA/Y2n5gSJQ==
    DB_USER: AgAd9cjxjwegctaeLg3Q7aA/hQX6mctmjWjOwzSouDrdN+VfTZE6Q5Y3b/rBsw9Hu+am9ZIrmeanpy+mYliLIyPllQ3pO+ep152vMAo3+YCrVLKmB3pjF+ohqSn0X5iwL2UFWKBDlw5Pbv8Yc6Pb7vq0NzotyYbyMXyXWbvbq/Xu4vQ8W6t2w6Mry1W30Y13uWY4ROILSEDv4C4BGTKPUzP6Gud9zDxbqN+asD9mr5P/v6EYItac4nmyyZF/Ir7c+fJT+nb1K4oO0Z0FENfAxrFPrsQsEyNPwCChmhjTUnB5mZz21lLSTSPZgohpE8HOtGwpPs7EZFx7ERdZ9eu+oHoM85OdaVZnGfP665ioiHdTPbzELTE6r73Jz8dbZ6kfVUkbGl2TRXKXoKpaX8pGI0eXcB4+HUlf4UZILDY22hjlGlH3zcmPnKcClP4SMrb4lxDYotRJclt8nL95e3zQu8A+WaqwYlr5UkYz5jCaOQDRvRLHcPCVWV7es0p+2ZZZos+TN+ETVJaewAgHlKuI8qENi4g/zVVc09d1r16iFfjswAUtYVXsvmv/FRkHau2FVTVBV9zqEIe+aUkkh3O3f/vnjJ06P+7BWvurVxM54NbkxAjYkTWlOfhOE7kTSnR1thGyBa9v9Ptys3Bbqaey8Sr0syZ86+q4T99vmXH9LevHx1q8VIo6pRsOWT3r7t/RF0B9y0izMaztFg==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-prod
    type: Opaque

