kind: PersistentVolume
apiVersion: v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "270"
  name: logs
  labels:
    intent: logs
spec:
  storageClassName: "ibmc-file-gold"
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: fsf-syd0101h-fz.service.softlayer.com
    path: /IBM02SEV304026_1149/data01/logs
