kind: PersistentVolume
apiVersion: v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "270"
  name: resources
  labels:
    intent: resources
spec:
  storageClassName: "ibmc-file-gold"
  capacity:
    storage: 100Mi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: fsf-syd0101h-fz.service.softlayer.com
    path: /IBM02SEV304026_1149/data01/resources
